export const CALCULATIONS_REQUEST = 'CALCULATIONS_REQUEST';
export const CALCULATIONS_SUCCESS = 'CALCULATIONS_SUCCESS';
export const CALCULATIONS_FAILED = 'CALCULATIONS_FAILED';
export const CALCULATIONS_UPDATE_DATA = 'CALCULATIONS_UPDATE_DATA';
export const CALCULATIONS_UPDATE_FIXED_COSTS = 'CALCULATIONS_UPDATE_FIXED_COSTS';
export const CALCULATIONS_UPDATE_FILE_NAME = 'CALCULATIONS_UPDATE_FILE_NAME';
export const CALCULATIONS_REDIRECTED = 'CALCULATIONS_REDIRECTED';
export const CALCULATIONS_RESET = 'CALCULATIONS_RESET';
