export const MAIL_VERIFICATION_REQUEST = 'MAIL_VERIFICATION_REQUEST';
export const MAIL_VERIFICATION_SUCCESS = 'MAIL_VERIFICATION_SUCCESS';
export const MAIL_VERIFICATION_FAILED = 'MAIL_VERIFICATION_FAILED';
